### ISSUE TITLE
Make the 'fields' key of nfts optional in the bcmr schema

### ISSUE THREAD

**Issue by mr-zwets** [bitjson/chip-bcmr#6]
This was discussed in private and it was concluded that the 'fields' key of nfts being required was a small oversight.
The schema becomes easier to digest when you can filter out all the optional fields so that why this change is relevant, to simplify the standard further.
Documenting it here so it isn't forgotten about.

**Comment by bitjson** [comment]
Thanks for identifying this issue @mr-zwets! I just pushed #7 which includes the correction. Please let me know what you think!
