### ISSUE TITLE
extend the standard with ability to publish the json directly

### ISSUE THREAD

**Issue by A60AB5450353F40E** [bitjson/chip-bcmr#9]
There was some talk in Tg channel initiated by Calin, asking why not extend the standard with ability to just put the data for simplest tokens directly on-chain, something like:

Current:
- `OP_RETURN <'BCMR'> <hash> [url]`

Proposed:
- `OP_RETURN <'BCMR'> <<hash> [url] | <blob>>`

So, one could just do `OP_RETURN <'BCMR'> <raw content of some file.json>` and for small registries it could maybe fit

Rationale: if people want the data on-chain, they will find a way to have it on-chain. If I really wanted to dump my registry on-chain I could go the round-about way and using the current specification:

I publish a TX with the blob in OP_RETURN and then I publish a BCMR TX with `OP_RETURN <'BCMR'> <hash> <'myopreturnsite.com?txid=123123...123&output_index=1'>` then I make a site that pulls from chain and serves the data stored in the referenced `txid:vout`.

Or, store it in the same TX's input script: `OP_RETURN <'BCMR'> <hash> <'myopreturnsite.com?input_index=1'>` mirroring ordinals inscription approach, and wallets could just be clever and skip the site entirely and read the input directly

**Comment by zander** [comment]
I would prefer to avoid the extra code-paths and just keep it simple.

Adding things in-line has various down-sides.

* size. Obviously people will not stop at the simplest thing.
* I suspect that 90% of the usecases that have tiny JSONS want this STILL want to point to an icon. Which would still be off-chain. (right?) So no gain had..
* The entire auth-chain now contains full registry data multiple times.
* privacy. Store stuf on chain and it can never be removed.
* All processors of data now suddenly have to have two ways to process data.
* Creators that allow tiny registies on-chain have to deal with frustrated users when that one extra field means it no longer fits.

Can of worms.

I don't want to implement this suggestion in my wallet.

ps. Does the original suggestor of this idea (calin) suggest that they will not want to implement the current spec? Because this suggestion only benefits if they don't ever want to actually fetch the BCMR from elsewhere.

**Comment by cculianu** [comment]
Maybe the `<blob>` isn't needed but -- would be great for the SLP-like case to be supported.

`<BCMR4DUMMIES> <NAME> <TICKER_SYMBOL> <DECIMALS> <HASH> <URL>`

**Comment by A60AB5450353F40E** [comment]
Actually this is compatible with "authchains", instead of attesting to the "big" BCMR, they'd be attesting to the "BCMR4DUMMIES", and it, too, would be updateable by tracing the authchain.

**Comment by bitjson** [comment]
Catching up here, thank you all for reviewing the spec!

I think @zander [covered many of the downsides above](https://github.com/bitjson/chip-bcmr/issues/9#issuecomment-1538774664); it would be a new code path that 100% of clients would be forced to implement, test, and maintain, but the new strategy also isn't likely to be usable by many professional projects (e.g. we can see that the  `description` equivalents on aggregators and in wallets for most ETH token projects would already exceed the current 220 byte limit).

At a higher level, it's really critical that we think clearly about metadata authentication – getting metadata to clients is easy, verifying that it isn't a scam is hard. [More discussion in this thread](https://github.com/bitjson/cashtokens/issues/50#issuecomment-1241116502):

> Until then, I just wanted to mention again: any system in which wallets "trust" data committed in genesis transactions will be vulnerable to impersonation. E.g. an attacker can create several "token genesis impersonations" for every token genesis transaction. The impersonations could share any/all the features of the "real" token genesis transactions: same "genesis data", same structure, and mined in the same block (the only difference would be the attackers control). That means an attacker can make "genesis metadata" protocols practically useless for all BCH users with only a few dollars a day in transaction fees. (See further discussion in my comments above.)

So publishing metadata on-chain can potentially be useful, but only if the client has already developed a trust relationship with a particular authbase/authchain as a known identity, and critically, **that identity will almost never be the issuer of the asset covered by the metadata**. It's a trusted data provider, like a block explorer, aggregator, wallet vendor, etc.

Even if you 100% trust a particular issuer with all of your assets, it's still wise to have some "separation of power" – you still don't want to blindly accept every metadata update they send you. If they get hacked and begin feeding your wallet lies, you might accept HackerCoins as RealMoney for hours before you find out about the breach on social media. 

**Metadata registries just formalize the existing, informal flow of metadata**: new tokens get created by issuers, old tokens get rebranded/re-issued/dividends/etc., and well-trusted entities bundle all that information into the software that actual users use. If the metadata published by a token issuer isn't totally misleading, the bundlers will generally just copy/paste it into their larger registry (from an on-chain broadcast, a website, or wherever), but that review step the security-critical moment. How metadata gets from issuers to bundlers is much less important than how verified metadata gets from bundlers to wallets.

**Comment by bitjson** [comment]
Also [copying a related comment from Telegram](https://t.me/cashtoken_devs/6795):

> One way to think about BCMRs: the purpose of a registry is to fully extract the subjective content/decisions that wallet, block explorers, and other clients have to make about handling and displaying on-chain identities and assets. Instead of hard-coding things like names, symbols, categories, decimal places, dates, descriptions, web addresses, NFT parsing strategies, etc. developers of software dealing with this stuff can delegate or work together on those items using a common interchange format.
>
> We've thought ahead in a few areas to minimize some future pain by standardizing "extensions", clearly defining authentication strategies and domains of control, and handling edge cases like dividends, asset re-issuance, chain splits, and identity compromises. Generally, the hope is that most issuers/clients/users don't need to worry about these more advanced details until further down the line. It's pretty easy to just grab names, symbols, and icons from a registry hosted on a website for now; as clients and the ecosystem grow, having a plan for those advanced use cases will hopefully cut down on technical debt and save development time.
>
> In fact, I'll bet some wallets won't even both adding "resolution" at all, either from a static URL or the on-chain identity-following strategy. The registry format is a good way to store and version control this stuff in your wallet project's source code ("embedded registries"), and you can just pull in reasonable metadata changes in well-known tokens/assets/etc before you release a new version. This is essentially what other ecosystems currently do, but they often don't share a common format, so metadata curation/authentication has become both a pain and a competitive advantage for several wallets and projects (and they often make a side business of selling access).

So asset issuers can always publish "primary source" BCMRs, but **the entities that really matter are the neutral parties** – wallets, block explorers, indexers, etc. – who review the metadata for honesty and package it up into "verified" BCMRs that they ship in their own software and/or re-publish for downstream applications.

**Comment by zquestz** [comment]
Just to chime in, I think having JSON directly in the OP_RETURN is a bad idea. Zander covered the issues comprehensively. I also don't think having multiple code paths to support the legacy SLP syntax is a win for anyone, the new registries have more features, and are easy to setup. SLP was a fun experiment, but not worth copying from.

**Comment by A60AB5450353F40E** [comment]
Ageed, I think it's ok to close this one now, @cculianu already implemented BCMR as per the current spec :)
